### ISSUE TITLE
Version 0.1.1 not on NPM

### ISSUE THREAD

**Issue by jsok** [lazd/karma-benchmark-reporter#1]
Hey is there any chance you can push the latest version to NPM? It only has 0.1.0.

Thanks :)

**Comment by meltuhamy** [comment]
+1  npm publish the update please @lazd  :)

**Comment by lazd** [comment]
0.1.1 is published! Please let me know if it doesn't work for any reason, npm had a tendency to not do things that are asked of it ;)
